### ISSUE TITLE
Version 3.18.0 required

### ISSUE THREAD

**Issue by chechulinYuri** [yandexmobile/metrica-plugin-unity#33]
10% of devices with android api level 30 have crash on start up.
I think version 3.18.0 of android plugin is required to fix that

`java.lang.SecurityException: getSerial: The user 10249 does not meet the requirements to access device identifiers.
     FATAL EXCEPTION: YMM-NC[]-15

java.lang.SecurityException: getSerial: The user 10249 does not meet the requirements to access device identifiers.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.os.IDeviceIdentifiersPolicyService$Stub$Proxy.getSerialForPackage(IDeviceIdentifiersPolicyService.java:162)
	at android.os.Build.getSerial(Build.java:175)
	at com.yandex.metrica.impl.ob.lt.a(SourceFile:60)
	at com.yandex.metrica.impl.ob.lt.<init>(SourceFile:48)
	at com.yandex.metrica.impl.ob.ls.a(SourceFile:45)
	at com.yandex.metrica.impl.ob.sd.a(SourceFile:304)
	at com.yandex.metrica.impl.ob.ca.a(SourceFile:63)
	at com.yandex.metrica.impl.ob.bi.b(SourceFile:27)
	at com.yandex.metrica.impl.ob.cc.b(SourceFile:78)
	at com.yandex.metrica.impl.ob.bh.a(SourceFile:92)
	at com.yandex.metrica.impl.ob.bh.run(SourceFile:75)
	at com.yandex.metrica.impl.ob.ur.execute(SourceFile:18)
	at com.yandex.metrica.impl.ob.vd.execute(SourceFile:15)
	at com.yandex.metrica.impl.ob.bb.run(SourceFile:90)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.telephony.TelephonyPermissions.reportAccessDeniedToReadIdentifiers(TelephonyPermissions.java:381)
	at com.android.internal.telephony.TelephonyPermissions.checkPrivilegedReadPermissionOrCarrierPrivilegePermission(TelephonyPermissions.java:323)
	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:257)
	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:233)
	at com.android.server.os.DeviceIdentifiersPolicyService$DeviceIdentifiersPolicy.getSerialForPackage(DeviceIdentifiersPolicyService.java:68)`

**Comment by chechulinYuri** [comment]
and this one for android api level 29

java.lang.Error: FATAL EXCEPTION [YMM-NC[]-14]
Unity version     : 2019.4.17f1
Device model      : Meberry M7
Device fingerprint: Meberry/M7Pro/M7Pro:10/QP1A.190711.020/vME140101:user/release-keys
Caused by
  at android.os.Parcel.createException (Parcel.java:2071)
  at android.os.Parcel.readException (Parcel.java:2039)
  at android.os.Parcel.readException (Parcel.java:1987)
  at android.os.IDeviceIdentifiersPolicyService$Stub$Proxy.getSerialForPackage (IDeviceIdentifiersPolicyService.java:159)
  at android.os.Build.getSerial (Build.java:162)
  at com.yandex.metrica.impl.ob.lt.a (SourceFile:60)
  at com.yandex.metrica.impl.ob.lt.<init> (SourceFile:48)
  at com.yandex.metrica.impl.ob.ls.a (SourceFile:45)
  at com.yandex.metrica.impl.ob.sd.a (SourceFile:304)
  at com.yandex.metrica.impl.ob.ca.a (SourceFile:63)
  at com.yandex.metrica.impl.ob.bi.b (SourceFile:27)
  at com.yandex.metrica.impl.ob.cc.b (SourceFile:78)
  at com.yandex.metrica.impl.ob.bh.a (SourceFile:92)
  at com.yandex.metrica.impl.ob.bh.run (SourceFile:75)
  at com.yandex.metrica.impl.ob.ur.execute (SourceFile:18)
  at com.yandex.metrica.impl.ob.vd.execute (SourceFile:15)
  at com.yandex.metrica.impl.ob.bb.run (SourceFile:90)
Caused by: android.os.RemoteException: 
  at com.android.internal.telephony.TelephonyPermissions.reportAccessDeniedToReadIdentifiers (TelephonyPermissions.java:417)
  at com.android.internal.telephony.TelephonyPermissions.checkReadDeviceIdentifiers (TelephonyPermissions.java:349)
  at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers (TelephonyPermissions.java:274)
  at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers (TelephonyPermissions.java:251)
  at com.android.server.os.DeviceIdentifiersPolicyService$DeviceIdentifiersPolicy.getSerialForPackage (DeviceIdentifiersPolicyService.java:67)
